version: '3'
services:
    psql-db:
        image: postgres:14
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
    express-api:
        build: .
        ports:
            - '3000:3000'
        environment:
            API_HOST: ${API_HOST}
            API_PORT: ${API_PORT}
            API_PREFIX: ${API_PREFIX}
            DB_HOST: 'psql-db'
            DB_PORT: 5432
            DB_USERNAME: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_DATABASE: ${POSTGRES_DB}
            EMAIL_SENDER: ${EMAIL_SENDER}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        depends_on:
            - psql-db
