version: '3'
services:
    psql-db:
        image: postgres:14
        environment:
            POSTGRES_USER: '${DB_HOST}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
    express-api:
        build: .
        ports:
            - '3000:3000'
        environment:
            API_HOST: '${API_HOST}'
            API_PORT: '${API_PORT}'
            API_PREFIX: '${API_PREFIX}'
            # DATABASE
            DB_HOST: '${DB_HOST}'
            DB_PORT: '${DB_PORT}'
            DB_NAME: '${DB_NAME}'
            DB_USER: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
            # FIREBASE AUTH
            FIREBASE_SERVICE_ACCOUNT_KEY_PATH: '${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}'
            # EMAIL SENDER
            EMAIL_SENDER: '${EMAIL_SENDER}'
            EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
        depends_on:
            - psql-db
